"""initial_schema_v2_postgresql

Revision ID: c6e60f611a1f
Revises: 
Create Date: 2026-08-31 18:46:24.766192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6e60f611a1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_v2',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_desc', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_v2',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_desc', sa.String(length=512), nullable=True),
    sa.Column('sprite_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move_v2',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('base_power', sa.SmallInteger(), nullable=False),
    sa.Column('accuracy', sa.SmallInteger(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('pp', sa.SmallInteger(), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.Column('short_desc', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_species_v2',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('base_species_id', sa.String(length=128), nullable=True),
    sa.Column('forme', sa.String(length=64), nullable=True),
    sa.Column('type1', sa.String(length=32), nullable=True),
    sa.Column('type2', sa.String(length=32), nullable=True),
    sa.Column('bst_hp', sa.SmallInteger(), nullable=False),
    sa.Column('bst_atk', sa.SmallInteger(), nullable=False),
    sa.Column('bst_def', sa.SmallInteger(), nullable=False),
    sa.Column('bst_spa', sa.SmallInteger(), nullable=False),
    sa.Column('bst_spd', sa.SmallInteger(), nullable=False),
    sa.Column('bst_spe', sa.SmallInteger(), nullable=False),
    sa.Column('abilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learnset_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sprite_url', sa.String(length=512), nullable=True),
    sa.Column('artwork_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['base_species_id'], ['pokemon_species_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'name', name='uq_tag_category_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team_variant_v2',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('size', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_v2',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ability_tag',
    sa.Column('ability_id', sa.String(length=128), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['ability_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ability_id', 'tag_id')
    )
    op.create_table('item_tag',
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    op.create_table('match_v2',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['trainer_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_v2_format', 'match_v2', ['format'], unique=False)
    op.create_table('move_tag',
    sa.Column('move_id', sa.String(length=128), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['move_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('move_id', 'tag_id')
    )
    op.create_table('pokemon_build',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('species_id', sa.String(length=128), nullable=True),
    sa.Column('ability_id', sa.String(length=128), nullable=True),
    sa.Column('item_id', sa.String(length=128), nullable=True),
    sa.Column('tera_type', sa.String(length=32), nullable=True),
    sa.Column('nature', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['ability_v2.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item_v2.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_summary_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=256), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('match_team_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=256), nullable=False),
    sa.Column('trainer_id', sa.String(length=128), nullable=False),
    sa.Column('player_slot', sa.String(length=2), nullable=False),
    sa.Column('team_variant_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_variant_id'], ['team_variant_v2.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_team_v2_match_id', 'match_team_v2', ['match_id'], unique=False)
    op.create_index('idx_match_team_v2_trainer_id', 'match_team_v2', ['trainer_id'], unique=False)
    op.create_index('idx_match_team_v2_variant_id', 'match_team_v2', ['team_variant_id'], unique=False)
    op.create_table('pokemon_build_move',
    sa.Column('build_id', sa.String(length=64), nullable=False),
    sa.Column('move_id', sa.String(length=128), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('slot BETWEEN 1 AND 4', name='ck_build_move_slot'),
    sa.ForeignKeyConstraint(['build_id'], ['pokemon_build.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['move_id'], ['move_v2.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'move_id')
    )
    op.create_index('idx_build_move_build_id', 'pokemon_build_move', ['build_id'], unique=False)
    op.create_index('idx_build_move_move_id', 'pokemon_build_move', ['move_id'], unique=False)
    op.create_table('pokemon_build_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=False),
    sa.Column('ev_hp', sa.SmallInteger(), nullable=False),
    sa.Column('ev_atk', sa.SmallInteger(), nullable=False),
    sa.Column('ev_def', sa.SmallInteger(), nullable=False),
    sa.Column('ev_spa', sa.SmallInteger(), nullable=False),
    sa.Column('ev_spd', sa.SmallInteger(), nullable=False),
    sa.Column('ev_spe', sa.SmallInteger(), nullable=False),
    sa.Column('iv_hp', sa.SmallInteger(), nullable=False),
    sa.Column('iv_atk', sa.SmallInteger(), nullable=False),
    sa.Column('iv_def', sa.SmallInteger(), nullable=False),
    sa.Column('iv_spa', sa.SmallInteger(), nullable=False),
    sa.Column('iv_spd', sa.SmallInteger(), nullable=False),
    sa.Column('iv_spe', sa.SmallInteger(), nullable=False),
    sa.Column('observed_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pokemon_build.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'ev_hp', 'ev_atk', 'ev_def', 'ev_spa', 'ev_spd', 'ev_spe', 'iv_hp', 'iv_atk', 'iv_def', 'iv_spa', 'iv_spd', 'iv_spe', name='uq_build_stats_spread')
    )
    op.create_table('team_variant_build',
    sa.Column('team_variant_id', sa.String(length=64), nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('slot BETWEEN 1 AND 6', name='ck_tvb_slot'),
    sa.ForeignKeyConstraint(['build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['team_variant_id'], ['team_variant_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_variant_id', 'build_id')
    )
    op.create_index('idx_team_variant_build_bid', 'team_variant_build', ['build_id'], unique=False)
    op.create_index('idx_team_variant_build_tv_id', 'team_variant_build', ['team_variant_id'], unique=False)
    op.create_table('turn_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=256), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turn_v2_match_id', 'turn_v2', ['match_id'], unique=False)
    op.create_table('match_archetype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('player_slot', sa.String(length=2), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['match_summary_v2.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_archetype_summary_id', 'match_archetype', ['summary_id'], unique=False)
    op.create_table('match_brought',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('player_slot', sa.String(length=2), nullable=False),
    sa.Column('build_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['match_summary_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_brought_build_id', 'match_brought', ['build_id'], unique=False)
    op.create_index('idx_match_brought_summary_id', 'match_brought', ['summary_id'], unique=False)
    op.create_table('turn_action_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('action_order', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('actor_build_id', sa.String(length=64), nullable=True),
    sa.Column('target_build_id', sa.String(length=64), nullable=True),
    sa.Column('move_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.String(length=512), nullable=True),
    sa.Column('raw_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['move_v2.id'], ),
    sa.ForeignKeyConstraint(['target_build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turn_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turn_action_v2_actor_id', 'turn_action_v2', ['actor_build_id'], unique=False)
    op.create_index('idx_turn_action_v2_move_id', 'turn_action_v2', ['move_id'], unique=False)
    op.create_index('idx_turn_action_v2_turn_id', 'turn_action_v2', ['turn_id'], unique=False)
    op.create_table('turn_board_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('p1a_build_id', sa.String(length=64), nullable=True),
    sa.Column('p1b_build_id', sa.String(length=64), nullable=True),
    sa.Column('p2a_build_id', sa.String(length=64), nullable=True),
    sa.Column('p2b_build_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['p1a_build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['p1b_build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['p2a_build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['p2b_build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turn_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id')
    )
    op.create_index('idx_board_state_turn_id', 'turn_board_state', ['turn_id'], unique=False)
    op.create_table('turn_field_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turn_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'side', 'tag_id', name='uq_tfc_turn_side_tag')
    )
    op.create_index('idx_field_cond_turn_id', 'turn_field_condition', ['turn_id'], unique=False)
    op.create_table('action_effect_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turn_action_id', sa.Integer(), nullable=False),
    sa.Column('target_build_id', sa.String(length=64), nullable=True),
    sa.Column('damage_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status_inflicted', sa.String(length=32), nullable=True),
    sa.Column('is_crit', sa.Boolean(), nullable=False),
    sa.Column('effectiveness', sa.String(length=32), nullable=True),
    sa.Column('ability_activated', sa.String(length=128), nullable=True),
    sa.Column('item_consumed', sa.String(length=128), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['target_build_id'], ['pokemon_build.id'], ),
    sa.ForeignKeyConstraint(['turn_action_id'], ['turn_action_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_effect_v2_action_id', 'action_effect_v2', ['turn_action_id'], unique=False)
    op.create_index('idx_action_effect_v2_target_bid', 'action_effect_v2', ['target_build_id'], unique=False)
    op.create_table('action_effect_stat_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effect_id', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(length=8), nullable=False),
    sa.Column('stages', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['effect_id'], ['action_effect_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stat_change_effect_id', 'action_effect_stat_change', ['effect_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stat_change_effect_id', table_name='action_effect_stat_change')
    op.drop_table('action_effect_stat_change')
    op.drop_index('idx_action_effect_v2_target_bid', table_name='action_effect_v2')
    op.drop_index('idx_action_effect_v2_action_id', table_name='action_effect_v2')
    op.drop_table('action_effect_v2')
    op.drop_index('idx_field_cond_turn_id', table_name='turn_field_condition')
    op.drop_table('turn_field_condition')
    op.drop_index('idx_board_state_turn_id', table_name='turn_board_state')
    op.drop_table('turn_board_state')
    op.drop_index('idx_turn_action_v2_turn_id', table_name='turn_action_v2')
    op.drop_index('idx_turn_action_v2_move_id', table_name='turn_action_v2')
    op.drop_index('idx_turn_action_v2_actor_id', table_name='turn_action_v2')
    op.drop_table('turn_action_v2')
    op.drop_index('idx_match_brought_summary_id', table_name='match_brought')
    op.drop_index('idx_match_brought_build_id', table_name='match_brought')
    op.drop_table('match_brought')
    op.drop_index('idx_match_archetype_summary_id', table_name='match_archetype')
    op.drop_table('match_archetype')
    op.drop_index('idx_turn_v2_match_id', table_name='turn_v2')
    op.drop_table('turn_v2')
    op.drop_index('idx_team_variant_build_tv_id', table_name='team_variant_build')
    op.drop_index('idx_team_variant_build_bid', table_name='team_variant_build')
    op.drop_table('team_variant_build')
    op.drop_table('pokemon_build_stats')
    op.drop_index('idx_build_move_move_id', table_name='pokemon_build_move')
    op.drop_index('idx_build_move_build_id', table_name='pokemon_build_move')
    op.drop_table('pokemon_build_move')
    op.drop_index('idx_match_team_v2_variant_id', table_name='match_team_v2')
    op.drop_index('idx_match_team_v2_trainer_id', table_name='match_team_v2')
    op.drop_index('idx_match_team_v2_match_id', table_name='match_team_v2')
    op.drop_table('match_team_v2')
    op.drop_table('match_summary_v2')
    op.drop_table('pokemon_build')
    op.drop_table('move_tag')
    op.drop_index('idx_match_v2_format', table_name='match_v2')
    op.drop_table('match_v2')
    op.drop_table('item_tag')
    op.drop_table('ability_tag')
    op.drop_table('trainer_v2')
    op.drop_table('team_variant_v2')
    op.drop_table('tag')
    op.drop_table('pokemon_species_v2')
    op.drop_table('move_v2')
    op.drop_table('item_v2')
    op.drop_table('ability_v2')
    # ### end Alembic commands ###
